### ISSUE TITLE
JSONField Deprecation 

### ISSUE THREAD

**Issue by pmourelle** [ambitioninc/django-issue#40]
Hi there. Project is still ongoing? Kudos for the development.
There's a deprecation warning happening for django >3:

```
issue.Issue.details: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
```

Is there any plan or future version for using django's JSONField instead? Thanks.

**Comment by fjcapdevila** [comment]
It would be nice to have this fixed anytime soon :)

**Comment by geophphrie** [comment]
This issue has been resolved.
